import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from sqlalchemy import create_engine, text
import google.generativeai as genai
import json
import sqlite3
import joblib
import os
import alpaca_trade_api as tradeapi

# ==========================================
# 1. APPLICATION SETUP & UI STYLING
# ==========================================
st.set_page_config(page_title="Macro-Sentiment System", layout="wide")
st.title("📈 Autonomous Agentic Analyzer")

st.warning("Legal Disclaimer: This system is for **educational and research purposes only**. The AI predictions, risk scores, and autonomous executions are simulated models and do not constitute financial advice. Algorithmic trading carries significant financial risk.", icon="⚠️")

st.markdown("""<style>[data-testid="stMetricValue"] { white-space: normal !important; word-wrap: break-word !important; font-size: 30px !important; line-height: 1.2 !important; }</style>""", unsafe_allow_html=True)

# Multi-API Authentication Sidebar
st.sidebar.markdown("### 🗝️ Intelligence Integration")
with st.sidebar.form("gemini_form"):
    api_key = st.text_input("Google Gemini API Key (Required):", type="password")
    submit_gemini = st.form_submit_button("Connect Intelligence")

if submit_gemini and api_key:
    st.sidebar.success("✅ Intelligence Core Online.")

st.sidebar.markdown("### 💸 Execution Integration (Optional)")
with st.sidebar.form("alpaca_form"):
    alpaca_key = st.text_input("Alpaca API Key:", type="password")
    alpaca_secret = st.text_input("Alpaca Secret Key:", type="password")
    submit_alpaca = st.form_submit_button("Connect Trading Webhook")

if submit_alpaca and alpaca_key and alpaca_secret:
    st.sidebar.success("✅ Trading Webhook Armed.")

# ==========================================
# 2. LOAD DATA & PRE-TRAINED MODELS
# ==========================================
@st.cache_data(ttl=60)
def fetch_from_db():
    engine = create_engine('sqlite:///macro_data.db')
    with engine.connect() as conn:
        try:
            conn.execute(text("ALTER TABLE macro_data ADD COLUMN Agent_Report TEXT"))
            conn.commit()
        except: pass 
    df = pd.read_sql('SELECT * FROM macro_data', engine)
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.sort_values(by='Date').reset_index(drop=True) 
    return df, df[df['Is_Anomaly'] == 1]

@st.cache_resource
def load_ml_models():
    """Loads pre-trained models generated by the backend ETL pipeline."""
    try:
        champion_model = joblib.load('champion_model.pkl')
        gmm_model = joblib.load('gmm_model.pkl')
        return champion_model, gmm_model
    except FileNotFoundError:
        st.error("🛑 Models not found. The nightly pipeline is currently building them.")
        st.stop()

@st.cache_data
def run_mapreduce(anomalies_df):
    all_words = []
    stop_words = {"the", "and", "to", "of", "a", "in", "for", "is", "on", "that", "by", "this", "with", "i", "you", "it", "not", "or", "be", "are", "from", "at", "as", "how", "will", "affect", "impacting", "analysts", "closely", "monitor"}
    for text_val in anomalies_df['Combined_News'].dropna():
        clean_text = str(text_val).lower().replace('.', '').replace(',', '').replace('"', '')
        mapped_words = clean_text.split()
        all_words.extend([w for w in mapped_words if w not in stop_words and len(w) > 3])
    word_counts = {}
    for word in all_words: word_counts[word] = word_counts.get(word, 0) + 1
    return pd.DataFrame(sorted(word_counts.items(), key=lambda x: x[1], reverse=True)[:10], columns=['Macro Theme', 'Frequency'])

df_joined, df_anomalies = fetch_from_db()
ml_model, gmm_model = load_ml_models()
anomaly_dates = df_anomalies['Date'].dt.strftime('%Y-%m-%d').tolist() if not df_anomalies.empty else []

# ==========================================
# 3. FRONTEND UI: ENTERPRISE TABS
# ==========================================
tab_overview, tab_agents, tab_graph, tab_sql = st.tabs(["📊 Market Overview", "⚖️ AI Analyst Debate & Execution", "🕸️ Knowledge Graph", "🕵️‍♂️ Database Query"])

with tab_overview:
    st.subheader("Market vs. Narrative Divergence")
    min_date, max_date = df_joined['Date'].min().date(), df_joined['Date'].max().date()
    date_range = st.slider("Select Historical Range for the Chart:", min_date, max_date, (min_date, max_date))
    mask = (df_joined['Date'].dt.date >= date_range[0]) & (df_joined['Date'].dt.date <= date_range[1])
    filtered_df, filtered_anomalies = df_joined.loc[mask], df_anomalies.loc[(df_anomalies['Date'].dt.date >= date_range[0]) & (df_anomalies['Date'].dt.date <= date_range[1])]
    
    filtered_themes_df = run_mapreduce(filtered_anomalies)

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=filtered_df['Date'].dt.strftime('%Y-%m-%d'), y=filtered_df['Price_Change_Pct'], name='DJIA % Change', line=dict(color='blue')))
    fig.add_trace(go.Scatter(x=filtered_df['Date'].dt.strftime('%Y-%m-%d'), y=filtered_df['Sentiment_Score'] * 5, name='FinBERT Sentiment', line=dict(color='green')))
    fig.add_trace(go.Scatter(x=filtered_anomalies['Date'].dt.strftime('%Y-%m-%d'), y=filtered_anomalies['Price_Change_Pct'], mode='markers', name='Anomalies', marker=dict(color='red', size=12)))
    fig.update_layout(xaxis_title="Date", yaxis_title="Percentage / Score", xaxis=dict(type='category', nticks=15))
    st.plotly_chart(fig, use_container_width=True)
    
    col_sandbox, col_mapreduce = st.columns(2)
    with col_sandbox:
        st.subheader("🎛️ AI ML Sandbox")
        sim_vix = st.slider("Fake Volatility (VIX)", min_value=10.0, max_value=85.0, value=20.0, step=0.5)
        sim_sent = st.slider("Fake News Sentiment", min_value=-1.0, max_value=1.0, value=0.0, step=0.05)
        
        # Predict using loaded model
        sim_prob = ml_model.predict_proba(pd.DataFrame([[sim_vix, sim_sent]], columns=['Volatility_VIX', 'Sentiment_Score']))[0][1] * 100
        sim_regime = gmm_model.predict(pd.DataFrame([[sim_vix, sim_sent]], columns=['Volatility_VIX', 'Sentiment_Score']))[0]
        st.metric("Anomaly Probability", f"{sim_prob:.2f}%")
        
        vix_centers = gmm_model.means_[:, 0]
        sorted_clusters = vix_centers.argsort()
        if sim_regime == sorted_clusters[0]: st.success("🟢 **Detected Market Regime:** Standard Trading")
        elif sim_regime == sorted_clusters[2]: st.error("🔴 **Detected Market Regime:** High Fear / Crisis")
        else: st.warning("🟠 **Detected Market Regime:** Correction Phase")
            
    with col_mapreduce:
        st.subheader("🗺️ MapReduce: Top Crisis Themes")
        max_freq = int(filtered_themes_df['Frequency'].max()) if not filtered_themes_df.empty else 100
        st.dataframe(filtered_themes_df, column_config={"Macro Theme": "Crisis Theme", "Frequency": st.column_config.ProgressColumn("Frequency", format="%d", min_value=0, max_value=max_freq)}, hide_index=True, use_container_width=True)

with tab_agents:
    st.subheader("⚖️ AI Analysts: Market Debate")
    if anomaly_dates:
        selected_date_str_tab2 = st.select_slider("🎯 Select Target Anomaly Date to Analyze:", options=anomaly_dates, key="tab2_date")
        sample = df_anomalies[df_anomalies['Date'].dt.strftime('%Y-%m-%d') == selected_date_str_tab2].iloc[0]
        
        if "live_report" not in st.session_state: st.session_state.live_report = None

        if st.button("Initiate Multi-Agent Debate", type="primary"):
            if not api_key: st.warning("Please save your Gemini API Key in the sidebar.")
            else:
                with st.spinner("Agents debating data..."):
                    genai.configure(api_key=api_key)
                    model = genai.GenerativeModel('gemini-2.5-flash')
                    top_themes = ", ".join(filtered_themes_df['Macro Theme'].head(3).tolist())
                    debate_prompt = f"""You are orchestrating a hedge fund debate regarding the market anomaly on {selected_date_str_tab2}. Data: Drop: {sample['Price_Change_Pct']:.2f}%, VIX: {sample['Volatility_VIX']:.2f}, Themes: {top_themes}. Respond ONLY with JSON: {{"optimistic_view": "...", "pessimistic_view": "...", "executive_summary": "...", "action": "BUY" or "SELL" or "HOLD", "confidence": 85}}"""
                    try:
                        response = model.generate_content(debate_prompt, generation_config={"response_mime_type": "application/json"})
                        st.session_state.live_report = json.loads(response.text)
                    except Exception as e: st.error(f"AI Error: {e}")

        if st.session_state.live_report:
            report = st.session_state.live_report
            col_bull, col_bear = st.columns(2)
            with col_bull: st.success(f"🟢 **Optimist:**\n\n{report['optimistic_view']}")
            with col_bear: st.error(f"🔴 **Pessimist:**\n\n{report['pessimistic_view']}")
            st.info(f"⚖️ **Executive Summary:**\n\n{report['executive_summary']}")
            col_act, col_conf = st.columns(2)
            col_act.metric("Action", report['action'])
            col_conf.metric("Confidence", f"{report['confidence']}%")

            st.markdown("---")
            st.subheader("🤖 Autonomous Execution Engine")
            if report['action'] in ["BUY", "SELL"]:
                if alpaca_key and alpaca_secret:
                    try:
                        api = tradeapi.REST(alpaca_key, alpaca_secret, base_url='https://paper-api.alpaca.markets')
                        order = api.submit_order(symbol='SPY', qty=1, side=report['action'].lower(), type='market', time_in_force='gtc')
                        st.success(f"✅ **Trade Executed!** Successfully submitted a {report['action']} order for 1 share of SPY via Alpaca.")
                    except Exception as trade_e: st.error(f"❌ Execution Failed. Verify your Alpaca keys. Error: {trade_e}")
                else: st.warning(f"⚠️ The AI recommended a {report['action']} order, but the Trading Webhook is disabled (Missing Alpaca Keys).")
            else: st.write("⏸️ The AI recommended a HOLD. No algorithmic trades executed.")

with tab_graph:
    st.subheader("🕸️ Live Entity Knowledge Graph")
    if anomaly_dates:
        selected_date_str_tab3 = st.select_slider("🎯 Select Target Date to Graph:", options=anomaly_dates, key="tab3_date")
        if st.button("Generate Relational Graph"):
            if not api_key: st.warning("Save Gemini Key in sidebar.")
            else:
                with st.spinner("Extracting Knowledge Graph..."):
                    genai.configure(api_key=api_key)
                    model = genai.GenerativeModel('gemini-2.5-flash')
                    try:
                        # STRICT MERMAID GUARDRAILS ADDED HERE
                        graph_prompt = f"""
                        Extract 5 entities from global news on {selected_date_str_tab3} and map cause-and-effect relationships.
                        
                        CRITICAL MERMAID.JS RULES (FAILURE TO FOLLOW WILL CRASH SYSTEM):
                        1. Node IDs MUST be single uppercase letters (A, B, C, D, E).
                        2. Node labels MUST contain ONLY alphanumeric characters and spaces. NO quotes, NO parentheses, NO colons, NO hyphens.
                        3. Strict Edge Syntax: A[Federal Reserve] --> B[Global Markets]
                        4. The code MUST start with 'graph TD;'
                        
                        Respond ONLY with JSON: 
                        {{
                            "mermaid_code": "graph TD; A[Inflation] --> B[Interest Rates];", 
                            "explanation": "..."
                        }}
                        """
                        response = model.generate_content(graph_prompt, generation_config={"response_mime_type": "application/json"})
                        graph_data = json.loads(response.text)
                        
                        # Clean any leftover markdown formatting the AI might have snuck in
                        mermaid_syntax = graph_data["mermaid_code"].replace('```mermaid', '').replace('```', '').replace('\n', '; ').strip()
                        if not mermaid_syntax.startswith("graph"):
                            mermaid_syntax = "graph TD; " + mermaid_syntax
                            
                        col_graph, col_info = st.columns([2, 1])
                        with col_graph:
                            st.components.v1.html(
                                f'<div class="mermaid">{mermaid_syntax}</div><script type="module">import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs";mermaid.initialize({{startOnLoad:true,theme:"dark"}});</script>', 
                                height=800, 
                                scrolling=True
                            )
                        with col_info: 
                            st.success(f"🤖 **Translation:**\n\n{graph_data['explanation']}")
                    except Exception as e: 
                        st.error(f"Graph Error: {e}")

with tab_sql:
    st.subheader("🕵️‍♂️ Database Agent (Text-to-SQL)")
    user_q = st.text_input("Ask a question (e.g., 'What was the highest VIX level?'):")
    if user_q:
        if not api_key: st.warning("API key required.")
        else:
            with st.spinner("Translating to SQL..."):
                genai.configure(api_key=api_key)
                try:
                    sql_resp = genai.GenerativeModel('gemini-2.5-flash').generate_content(f"Write SQLite query for table `macro_data`. Columns: `Date`, `Price_Change_Pct`, `Volatility_VIX`, `Sentiment_Score`, `Is_Anomaly`. Question: {user_q}. Return ONLY raw SQL string.")
                    raw_sql = sql_resp.text.replace('```sql', '').replace('```', '').strip()
                    st.code(raw_sql, language="sql")
                    with create_engine('sqlite:///macro_data.db').connect() as conn:
                        st.dataframe(pd.read_sql(text(raw_sql), conn), hide_index=True)
                except Exception as e: st.error(f"SQL Error: {e}")
